name: Update Sea Bright Peaks Cache

on:
  workflow_dispatch:
  schedule:
    - cron: "*/30 * * * *"  # every 30 minutes

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Run updater
        run: node tools/update_seabright_peaks_navd88.js

      - name: Commit & push if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data/seabright_peaks_navd88.json
          if git diff --cached --quiet; then
            echo "No changes."
            exit 0
          fi
          git commit -m "Update Sea Bright peaks cache"
          git push
