name: Update Sea Bright Peaks (NAVD88)

on:
  workflow_dispatch:
  schedule:
    - cron: "15,45 * * * *"  # every 30 min at :15 and :45 (UTC)

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Run updater
        run: node tools/update_seabright_peaks_navd88.js

      - name: Commit and push if changed
        run: |
          git status
          git diff --quiet && echo "No changes" && exit 0
          git add data/seabright_peaks_navd88.json
          git commit -m "Update Sea Bright peaks"
          git push
